# Generated by Django 4.0.1 on 2022-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reishop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['cloth_date_release'], 'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_brand',
            field=models.CharField(max_length=200, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_date_release',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_size',
            field=models.CharField(max_length=200, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Number'),
        ),
    ]
