# Generated by Django 4.0.2 on 2022-02-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reishop', '0004_alter_clothes_category_alter_clothes_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
